environment:
  matrix:
#    - PYTHON: "C:\\Python27"
#      TOX_ENV: "py27"

    - PYTHON: "C:\\Python36"
      TOX_ENV: "py36"


#init:
#  - "%PYTHON%/python -V"
#  - "%PYTHON%/python -c \"import struct;print( 8 * struct.calcsize(\'P\'))\""

install:
  - "%PYTHON%/Scripts/easy_install -U pip"
  - "%PYTHON%/Scripts/pip install --upgrade setuptools pip"
  - "%PYTHON%/Scripts/pip install pytest"
  - "%PYTHON%/Scripts/pip install ."
  - "%PYTHON%/Scripts/pip install sympy matplotlib numpy pandas holoviews bokeh"

build: false

test_script:
#  - cmd: "%PYTHON%/Scripts/tox -e %TOX_ENV%"
  - cmd: py.test -v tests --nbval --current-env --sanitize-with tests\sanitize_defaults.cfg --ignore tests\ipynb-test-samples

#after_test:
#  - "%PYTHON%/python setup.py bdist_wheel --universal"
#  - ps: "ls dist"

#artifacts:
#  - path: dist\*

#on_success:
#  - TODO: upload the content of dist/*.whl to a public wheelhouse
